<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
                background-color: #000000;
                background-image: url("images/background.jpg");
            }

            h1 {
                color: #FFFFFF;
                letter-spacing: -3px;
               // font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 500;

                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1><span>Rom</span><span style="color:#0099FF;">Sync</span><span style="color:#FF5500;"><i>2</i></span></h1>
        <?php if (isset($version)) : ?>
             <h2>version: <?=htmlspecialchars($version);?></h2>
        <?php endif; ?>
        <?php if (isset($version)) : ?>
            <h2>Database Status: <?=htmlspecialchars($dbstatus);?><?=htmlspecialchars($serverip);?></h2>

        <?php endif; ?>
       <!-- <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
   -->
    </body>
</html>
