<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type='text/css' href="/css/style.css" />
    </head>
    <body>
        <h1><span>Rom</span><span style="color:#0099FF;">Sync</span><span style="color:#FF5500;"><i>2</i></span></h1>
        <?php if (isset($version)) : ?>
             <h2>version: <?=htmlspecialchars($version);?></h2>
        <?php endif; ?>
        <?php if (isset($version)) : ?>
        <p>
            IP Address: <?=$ip?><br/>
            Database Status: <?=($database->status)?'OK':'FAIL'?><br/>
            Database IP: <?=($database->ip)?><br/>
            Database PORT: <?=($database->port)?><br/>
        </p>
        <?php endif; ?>
       <!-- <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
   -->
    </body>
</html>
