<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type='text/css' href="/css/style.css" />
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
                background-color: #000000;
                background-image: url("api/image/cpo background mfg_1");
            }
            h1 {
                color: #FFFFFF;
                letter-spacing: -3px;
                font-size: 100px;
                font-weight: 500;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1><span>Rom</span><span style="color:#0099FF;">Sync</span><span style="color:#FF5500;"><i>2</i></span></h1>
        
    </body>
</html>
